Repository emberjs/ember-jquery, pull requests merged in 2021-06, with the labels that each got.

#326 Avoid triggering Component reopen deprecation
  vendor/jquery/component.dollar.js
Labels: bug

#342 Drop support for Node 10, 13, and 15.
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#343 Update release setup
  CHANGELOG.md
  RELEASE.md
  package.json
Labels: internal

#344 Update broccoli based dependencies to latest
  package.json
  yarn.lock
Labels: internal

#345 Update ember-cli-babel to latest for Ember 3.27 compatibility
  package.json
  yarn.lock
Labels: bug

#347 Include `Ember.Component.prototype.$` deprecation regardless of Ember version
  index.js
  package.json
Labels: enhancement
